<a href="https://colab.research.google.com/github/mars241/PYTHON/blob/main/AAM-WCS-2_2_ML_Classification_KNN_distances_with_Pokemons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge - Attrapez-les tous "POKÉMON"

Un champion du monde Pokémon (oui, cela existe) a entendu parler de tes connaissances en Machine Learning et demande ton expertise.

Le champion a l'habitude d'utiliser les Pokemon suivants : Mewtwo, Lugia, Rayquaza, Giratina, Dialga, et Palkia. Mais pour sa prochaine compétition, il est interdit d'utiliser un Pokémon légendaire. Un pokemon est soit légendaire, soit non-légendaire. La dernière colonne du dataset indique True ou False suivant les cas.
Le champion devra donc remplacer ses Pokemon légendaires préférés par d'autres Pokémons non-légendaires, avec des caractéristiques similaires. C'est là que tu interviens !

Pour l'aider, suis les étapes suivantes :

1. Importe le dataset pokemon.csv[https://raw.githubusercontent.com/murpi/wilddata/master/pokemon.csv] 
Chaque ligne représente un pokemon, avec ses différentes caractéristiques (attaque, défense, vitesse, etc...), ainsi que la colonne "légendaire".
2. Entraine l'algorithme NN en utilisant l'ensemble des colonnes numériques en variables explicatives X.
Les valeurs nulles (NaN) posent problème à l'ensemble des algorithmes. Ici, pour simplifier, tu peux supprimer la colonne concernée avant d'entrainer ton modèle.
Pas besoin de traintestsplit dans ce cas précis : en effet, sinon tu chercheras les voisins sur un sous-échantillon. Alors qu'il y a peut-être des voisins plus proche.
Pas besoin de predict ou de score non plus : nous calculons uniquement des distances.
Utilise la fonction kneighbors() pour trouver le ou les Pokémons le(s) plus proche(s) de chacun des Pokémon légendaires que le champion a l'habitude d'utiliser.
Fais des recommandations de Pokémon à utiliser par le champion pour sa prochaine compétition, en lui priorisant par distance. Evidemment, ta recommandation ne doit pas indiquer un autre pokemon légendaire, même si ce dernier est très proche...
Critères de validation
Les solutions sont dans un notebook et peuvent être lues par toute personne ayant le lien.
Il y a une liste de recommandations de Pokémon.
La recommandation est basée sur l'utilisation de k-NN.

# METHODE 1 :

Le(s) Méthode(s) utilisée(s) est (sont) essentiellement la methode de classifications par des fonctions(approche statistique & mathématique) qui se comportent comme des bibliothèques, et des dictionnaires ainsi que la la programmation orienté objet(OOP); utilisation des classes, instances, méthode ect...:

# Aperçu de la data:

#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
5,Charmander,Fire,,39,52,43,60,50,65,1,False
6,Charmeleon,Fire,,58,64,58,80,65,80,1,False
7,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
8,Mega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
9,Mega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
10,Squirtle,Water,,44,48,65,50,64,43,1,False
11,Wartortle,Water,,59,63,80,65,80,58,1,False
12,Blastoise,Water,,79,83,100,85,105,78,1,False
13,Mega Blastoise,Water,,79,103,120,135,115,78,1,False
14,Caterpie,Bug,,45,30,35,20,20,45,1,False
15,Metapod,Bug,,50,20,55,25,25,30,1,False
16,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
17,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
18,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
19,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
20,Mega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False

In [4]:
# Aperçu de la dataset POKÉMON avec "pandas"
import pandas as pd

df_pokemon = pd.read_csv("https://raw.githubusercontent.com/murpi/wilddata/master/pokemon.csv" ,sep=';')

In [5]:
df_pokemon.head(20)

# Name,Type 1 & Type 2 sont les variables à étudier(Donné d'entrée & cibles:variable explicative et variable(s) expliqué(s): les futures k-plus proches voisins)

   #,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0   1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,F...
1    2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2   3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,...
3   4,Mega Venusaur,Grass,Poison,80,100,123,122,12...
4        5,Charmander,Fire,,39,52,43,60,50,65,1,False
5        6,Charmeleon,Fire,,58,64,58,80,65,80,1,False
6   7,Charizard,Fire,Flying,78,84,78,109,85,100,1,...
7   8,Mega Charizard X,Fire,Dragon,78,130,111,130,...
8   9,Mega Charizard Y,Fire,Flying,78,104,78,159,1...
9        10,Squirtle,Water,,44,48,65,50,64,43,1,False
10      11,Wartortle,Water,,59,63,80,65,80,58,1,False
11    12,Blastoise,Water,,79,83,100,85,105,78,1,False
12  13,Mega Blastoise,Water,,79,103,120,135,115,78...
13         14,Caterpie,Bug,,45,30,35,20,20,45,1,False
14          15,Metapod,Bug,,50,20,55,25,25,30,1,False
15  16,Butterfree,Bug,Flying,60,45,50,90,80,70,1,F...
16     17,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17     18,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18   19,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19  20,Mega Beedrill,Bug,Poison,65,150,40,15,80,14...

In [ ]:
# Mise en place du calclule des distances entre k vosins des pokémons et optimisations de ces dernières

import pandas as pd # Biblothèque pandas
import math # Fonctions Mathématiques
import numpy as np # Biblothèque Numpy
import operator #Les "Opérateurs standards" en tant que fonctions pour utiliser ces dernières(fct)!

#TOPO sur le module 'operator'
#Le module operator fournit un ensemble de fonctions correspondant aux opérateurs natifs de Python. Par exemple, operator.add(x, y) correspond à l'expression x+y. 
#Les noms de la plupart de ces fonctions sont ceux utilisés par les méthodes spéciales, sans les doubles tirets bas.
#Pour assurer la rétrocompatibilité, la plupart de ces noms ont une variante avec les doubles tirets bas ;
#la forme simple est cependant à privilégier pour des raisons de clarté
# En général, les opérations logiques s'appliquent aussi à tous les objets et implémentent les tests de vérité, d'identité et les opérations booléennes :
#operator.not_(obj)
#operator.__not__(obj)

 
# Défintion de la fonction contenant le(s) test(s) d'entrainement/ échantillon test, caractéristiques et initialisation de la distance:
def calc_euclidean(train_data, test_data, train_point, test_point, features):
	total_dist = 0

	for feature in features:

		dist = math.pow(test_data.loc[test_point, feature] - train_data.loc[train_point, feature], 2)
		total_dist += dist

	# d = sqrt((a1-b1)^2 + (a2-b2)^2 + (a3-b3)^2 + (a4-b4)^2) #Distance eudienne entre 2 points est racine_carré(différence des-coordonnées de ces points: le tout au carré!)
	return math.sqrt(total_dist)

def det_nearest_neighbors(train_data, test_data, test_point, features, k):
	# Boucle sur tout et calcule la distance euclidienne en appelant l'utilisation des dictionnaires
	dist_dict = {}

	for train_point in train_data.index:
		# Définir l'index du point d'entrainement "train' plus la distance euclidienne
		dist_dict[train_point] = calc_euclidean(train_data, test_data, train_point, test_point, features)

	# Obtenez les k valeurs les plus élevées
	dict_top_k = sorted(dist_dict, key=dist_dict.get, reverse=True)[:k]

	return dict_top_k


def KNN(test_data, train_data, features, target_col_name, k):
	for test_point in test_data.index:
		# Trouver le nombre k de voisins les plus proches
		nearest_neighbors = det_nearest_neighbors(train_data, test_data, test_point, features, k)

	  # Convertir les index en classes
		nearest_neighbors = train_data[train_data.index.isin(nearest_neighbors)]

		# Compter, grouper par classe
		agg_class = nearest_neighbors.groupby(target_col_name).size()
		
		# L'index maximum (Max count :"idxmax()") est une nouvelle classe
		test_data.loc[test_point, 'classify'] = agg_class.idxmax()
	
	# Déterminer la précision (coefficient de proportionalité entre le coeff de classification sur celui du test) avec la variable "accuracy"
	len_classify_equals_target = len(test_data[test_data[target_col_name] == test_data['classify']].index) 
	len_test_data = len(test_data.index)
	accuracy = len_classify_equals_target / len_test_data

In [ ]:
# Utilisation 

import pandas as pd # Biblothèque pandas
import math # Fonctions Mathématiques
import numpy as np # Biblothèque Numpy
import operator #Les "Opérateurs standards" en tant que fonctions pour utiliser ces dernières(fct)!
 

# Importez la/le(s) function/ module/ bibliothèque/ package relatif à l'agorithme KNN & les bayésiens
import KNN as knn
import bayesian as bayes



def main():
	# prepare la Data
	# charger le jeu de données pokemon.
	data = pd.read_csv("./Pokemon.csv")
	# Determine le target
	target_col_name = 'Type 1'

	# Caractéristiques 
	# On décide de ne pas utiliser 'Légendaire' et 'Génération' car la variation est trop faible. 
	# Les classes comme 'Bug' n'ont pas de carte légendaire, ce qui entraîne une erreur : 'Divide by zero error'.
	features = ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

	
  # Séparation de l'échantillon du dataset test/training "train" (80/20)
	msk = np.random.rand(len(data)) < 0.80
	train_data = data[msk]
	test_data = data[~msk]

	# Ajouter une colonne "classify" pour classifier par leurs index
	test_data['classify'] = test_data.index

	# Determine k = n^0.5
	k = int(math.pow(len(data.index), 0.5))

	# Obtenir des résultats
	test_data_knn, accuracy_knn = knn.KNN(test_data, train_data, features, target_col_name, k)
	test_data_bayes, accuracy_bayes = bayes.gaussian_naive_bayes(test_data, train_data, features, target_col_name)

	# Imprimer la précisionj
	print('Accuracy KNN classifier: ' + str(accuracy_knn))
	print('Accuracy Gaussian naive bayes classifier: ' + str(accuracy_bayes))

if __name__ == '__main__':
    main()